package it.university.Interfaces;

import it.university.model.Classroom;

public interface IClassroom extends IGeneric<Classroom, String>{
    //COME PER LE ALTRE INTERFACCE, I METODI COMUNI VENGONO INTESTATI NELL'INTERFACCIA GENERICA, IN QUESTO CASO E' STATO PASSATO
    //STRING A POSTO CHE INTEGER PERCHè IL CODICE è UNA STRINGA

    //ALL'INTERNO DI QUESTA CLASSE POSSO AGGIUNGERE DEI METODI CHE SONO INERENTI SOLO E SOLAMENTE A QUESTA CLASSE
}
