package it.university.Interfaces;

import java.util.List;

//QUESTA E' UNA CLASSE INTERFACCIA CHE USA I TIPI DI DATO GENERICI.

//ESSEDO CHE I METODI (findById, findAll, save) SONO COMUNI IN QUASI TUTTE LE CLASSI REPOSITORY ABBIAMO DECIDO DI INVOCARE QUESTI METODO
//UNA VOLTA SOLAMENTE TRAMITE L'UTILIZZO DEI TIPI DI DATO GENERICI.

public interface IGeneric<OGGETTO,IDENTIFICATIVO>{
    OGGETTO findById(IDENTIFICATIVO id);
    List<OGGETTO> findAll();
    void save(OGGETTO utente);
}
